// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  GeneratedImagesGetGeneratedImageData,
  GeneratedImagesGetGeneratedImageResponse,
  GeneratedImagesListGeneratedImagesData,
  GeneratedImagesListGeneratedImagesForPromptData,
  GeneratedImagesListGeneratedImagesForPromptResponse,
  GeneratedImagesListGeneratedImagesForSceneData,
  GeneratedImagesListGeneratedImagesForSceneResponse,
  GeneratedImagesListGeneratedImagesResponse,
  GeneratedImagesRemixGeneratedImageData,
  GeneratedImagesRemixGeneratedImageResponse,
  GeneratedImagesStreamGeneratedImageFileData,
  GeneratedImagesStreamGeneratedImageFileResponse,
  GeneratedImagesTriggerImageGenerationData,
  GeneratedImagesTriggerImageGenerationResponse,
  GeneratedImagesUpdateImageApprovalData,
  GeneratedImagesUpdateImageApprovalResponse,
  ImagePromptsGetImagePromptData,
  ImagePromptsGetImagePromptResponse,
  ImagePromptsListPromptsForBookData,
  ImagePromptsListPromptsForBookResponse,
  ImagePromptsListPromptsForSceneData,
  ImagePromptsListPromptsForSceneResponse,
  ItemsCreateItemData,
  ItemsCreateItemResponse,
  ItemsDeleteItemData,
  ItemsDeleteItemResponse,
  ItemsReadItemData,
  ItemsReadItemResponse,
  ItemsReadItemsData,
  ItemsReadItemsResponse,
  ItemsUpdateItemData,
  ItemsUpdateItemResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginTestTokenResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  SceneExtractionsGetFilterOptionsResponse,
  SceneExtractionsGetSceneExtractionData,
  SceneExtractionsGetSceneExtractionResponse,
  SceneExtractionsListSceneExtractionsData,
  SceneExtractionsListSceneExtractionsResponse,
  SceneRankingsGetSceneRankingData,
  SceneRankingsGetSceneRankingResponse,
  SceneRankingsListSceneRankingHistoryData,
  SceneRankingsListSceneRankingHistoryResponse,
  SceneRankingsListTopSceneRankingsData,
  SceneRankingsListTopSceneRankingsResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserMeResponse,
  UsersDeleteUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersReadUserMeResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersUpdateUserData,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdateUserResponse,
  UtilsHealthCheckResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
} from "./types.gen"

export class GeneratedImagesService {
  /**
   * List Generated Images
   * List generated images with optional filters and pagination.
   * @param data The data for the request.
   * @param data.book
   * @param data.chapter
   * @param data.sceneId
   * @param data.promptId
   * @param data.provider
   * @param data.model
   * @param data.approval
   * @param data.newestFirst
   * @param data.limit
   * @param data.offset
   * @returns GeneratedImageListResponse Successful Response
   * @throws ApiError
   */
  public static listGeneratedImages(
    data: GeneratedImagesListGeneratedImagesData = {},
  ): CancelablePromise<GeneratedImagesListGeneratedImagesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/generated-images",
      query: {
        book: data.book,
        chapter: data.chapter,
        scene_id: data.sceneId,
        prompt_id: data.promptId,
        provider: data.provider,
        model: data.model,
        approval: data.approval,
        newest_first: data.newestFirst,
        limit: data.limit,
        offset: data.offset,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Generated Image
   * Fetch a single generated image by identifier with full context.
   * Returns image metadata along with prompt text and raw scene text.
   * @param data The data for the request.
   * @param data.imageId
   * @param data.includePrompt
   * @param data.includeScene
   * @returns GeneratedImageWithContext Successful Response
   * @throws ApiError
   */
  public static getGeneratedImage(
    data: GeneratedImagesGetGeneratedImageData,
  ): CancelablePromise<GeneratedImagesGetGeneratedImageResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/generated-images/{image_id}",
      path: {
        image_id: data.imageId,
      },
      query: {
        include_prompt: data.includePrompt,
        include_scene: data.includeScene,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Image Approval
   * Update the approval status of a generated image.
   * @param data The data for the request.
   * @param data.imageId
   * @param data.requestBody
   * @returns GeneratedImageRead Successful Response
   * @throws ApiError
   */
  public static updateImageApproval(
    data: GeneratedImagesUpdateImageApprovalData,
  ): CancelablePromise<GeneratedImagesUpdateImageApprovalResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/generated-images/{image_id}/approval",
      path: {
        image_id: data.imageId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Stream Generated Image File
   * Stream the binary image file for a generated image.
   * @param data The data for the request.
   * @param data.imageId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static streamGeneratedImageFile(
    data: GeneratedImagesStreamGeneratedImageFileData,
  ): CancelablePromise<GeneratedImagesStreamGeneratedImageFileResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/generated-images/{image_id}/content",
      path: {
        image_id: data.imageId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Generated Images For Scene
   * Return generated images for a specific scene extraction.
   * @param data The data for the request.
   * @param data.sceneId
   * @param data.provider
   * @param data.model
   * @param data.newestFirst
   * @param data.limit
   * @param data.offset
   * @param data.includePrompt
   * @param data.includeScene
   * @returns GeneratedImageListResponse Successful Response
   * @throws ApiError
   */
  public static listGeneratedImagesForScene(
    data: GeneratedImagesListGeneratedImagesForSceneData,
  ): CancelablePromise<GeneratedImagesListGeneratedImagesForSceneResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/generated-images/scene/{scene_id}",
      path: {
        scene_id: data.sceneId,
      },
      query: {
        provider: data.provider,
        model: data.model,
        newest_first: data.newestFirst,
        limit: data.limit,
        offset: data.offset,
        include_prompt: data.includePrompt,
        include_scene: data.includeScene,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Generated Images For Prompt
   * Return generated images for a specific image prompt.
   * @param data The data for the request.
   * @param data.promptId
   * @param data.provider
   * @param data.model
   * @param data.newestFirst
   * @param data.limit
   * @param data.offset
   * @returns GeneratedImageListResponse Successful Response
   * @throws ApiError
   */
  public static listGeneratedImagesForPrompt(
    data: GeneratedImagesListGeneratedImagesForPromptData,
  ): CancelablePromise<GeneratedImagesListGeneratedImagesForPromptResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/generated-images/prompt/{prompt_id}",
      path: {
        prompt_id: data.promptId,
      },
      query: {
        provider: data.provider,
        model: data.model,
        newest_first: data.newestFirst,
        limit: data.limit,
        offset: data.offset,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Remix Generated Image
   * Trigger subtle remix prompt generation for a specific generated image.
   * @param data The data for the request.
   * @param data.imageId
   * @param data.requestBody
   * @returns GeneratedImageRemixResponse Successful Response
   * @throws ApiError
   */
  public static remixGeneratedImage(
    data: GeneratedImagesRemixGeneratedImageData,
  ): CancelablePromise<GeneratedImagesRemixGeneratedImageResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/generated-images/{image_id}/remix",
      path: {
        image_id: data.imageId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Trigger Image Generation
   * Trigger image generation for a selection of prompts.
   *
   * This endpoint allows you to generate images based on various filters:
   * - By book_slug (optionally with chapter_range)
   * - By specific scene_ids
   * - By specific prompt_ids
   *
   * In dry-run mode, it will return a count of 0 and no IDs.
   * Otherwise, it returns the list of generated image IDs.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns GeneratedImageGenerateResponse Successful Response
   * @throws ApiError
   */
  public static triggerImageGeneration(
    data: GeneratedImagesTriggerImageGenerationData,
  ): CancelablePromise<GeneratedImagesTriggerImageGenerationResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/generated-images/generate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ImagePromptsService {
  /**
   * List Prompts For Scene
   * Return image prompts for a specific scene.
   * @param data The data for the request.
   * @param data.sceneId
   * @param data.limit
   * @param data.newestFirst
   * @param data.modelName
   * @param data.promptVersion
   * @param data.includeScene
   * @returns ImagePromptListResponse Successful Response
   * @throws ApiError
   */
  public static listPromptsForScene(
    data: ImagePromptsListPromptsForSceneData,
  ): CancelablePromise<ImagePromptsListPromptsForSceneResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/image-prompts/scene/{scene_id}",
      path: {
        scene_id: data.sceneId,
      },
      query: {
        limit: data.limit,
        newest_first: data.newestFirst,
        model_name: data.modelName,
        prompt_version: data.promptVersion,
        include_scene: data.includeScene,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Prompts For Book
   * List prompts across a book with optional filters and pagination.
   * @param data The data for the request.
   * @param data.bookSlug
   * @param data.chapterNumber
   * @param data.modelName
   * @param data.promptVersion
   * @param data.styleTag
   * @param data.newestFirst
   * @param data.limit
   * @param data.offset
   * @param data.includeScene
   * @returns ImagePromptListResponse Successful Response
   * @throws ApiError
   */
  public static listPromptsForBook(
    data: ImagePromptsListPromptsForBookData,
  ): CancelablePromise<ImagePromptsListPromptsForBookResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/image-prompts/book/{book_slug}",
      path: {
        book_slug: data.bookSlug,
      },
      query: {
        chapter_number: data.chapterNumber,
        model_name: data.modelName,
        prompt_version: data.promptVersion,
        style_tag: data.styleTag,
        newest_first: data.newestFirst,
        limit: data.limit,
        offset: data.offset,
        include_scene: data.includeScene,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Image Prompt
   * Fetch a single image prompt by identifier.
   * @param data The data for the request.
   * @param data.promptId
   * @param data.includeScene
   * @returns ImagePromptRead Successful Response
   * @throws ApiError
   */
  public static getImagePrompt(
    data: ImagePromptsGetImagePromptData,
  ): CancelablePromise<ImagePromptsGetImagePromptResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/image-prompts/{prompt_id}",
      path: {
        prompt_id: data.promptId,
      },
      query: {
        include_scene: data.includeScene,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ItemsService {
  /**
   * Read Items
   * Retrieve items.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ItemsPublic Successful Response
   * @throws ApiError
   */
  public static readItems(
    data: ItemsReadItemsData = {},
  ): CancelablePromise<ItemsReadItemsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Item
   * Create new item.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static createItem(
    data: ItemsCreateItemData,
  ): CancelablePromise<ItemsCreateItemResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/items/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Item
   * Get item by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static readItem(
    data: ItemsReadItemData,
  ): CancelablePromise<ItemsReadItemResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Item
   * Update an item.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static updateItem(
    data: ItemsUpdateItemData,
  ): CancelablePromise<ItemsUpdateItemResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Item
   * Delete an item.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteItem(
    data: ItemsDeleteItemData,
  ): CancelablePromise<ItemsDeleteItemResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class SceneExtractionsService {
  /**
   * List Scene Extractions
   * Return a paginated list of scene extractions with optional filters.
   * @param data The data for the request.
   * @param data.page
   * @param data.pageSize
   * @param data.bookSlug
   * @param data.chapterNumber
   * @param data.decision
   * @param data.hasRefined
   * @param data.search
   * @param data.startDate
   * @param data.endDate
   * @param data.order
   * @returns SceneExtractionListResponse Successful Response
   * @throws ApiError
   */
  public static listSceneExtractions(
    data: SceneExtractionsListSceneExtractionsData = {},
  ): CancelablePromise<SceneExtractionsListSceneExtractionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/scene-extractions/",
      query: {
        page: data.page,
        page_size: data.pageSize,
        book_slug: data.bookSlug,
        chapter_number: data.chapterNumber,
        decision: data.decision,
        has_refined: data.hasRefined,
        search: data.search,
        start_date: data.startDate,
        end_date: data.endDate,
        order: data.order,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Filter Options
   * Expose the available filter options for scene extractions.
   * @returns SceneExtractionFilterOptions Successful Response
   * @throws ApiError
   */
  public static getFilterOptions(): CancelablePromise<SceneExtractionsGetFilterOptionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/scene-extractions/filters",
    })
  }

  /**
   * Get Scene Extraction
   * Fetch a single scene extraction by its identifier.
   * @param data The data for the request.
   * @param data.sceneId
   * @returns SceneExtractionRead Successful Response
   * @throws ApiError
   */
  public static getSceneExtraction(
    data: SceneExtractionsGetSceneExtractionData,
  ): CancelablePromise<SceneExtractionsGetSceneExtractionResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/scene-extractions/{scene_id}",
      path: {
        scene_id: data.sceneId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class SceneRankingsService {
  /**
   * List Top Scene Rankings
   * Return the highest ranked scenes for a book with optional filters.
   * @param data The data for the request.
   * @param data.bookSlug
   * @param data.limit
   * @param data.modelName
   * @param data.promptVersion
   * @param data.weightConfigHash
   * @param data.includeScene
   * @returns SceneRankingListResponse Successful Response
   * @throws ApiError
   */
  public static listTopSceneRankings(
    data: SceneRankingsListTopSceneRankingsData,
  ): CancelablePromise<SceneRankingsListTopSceneRankingsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/scene-rankings/top",
      query: {
        book_slug: data.bookSlug,
        limit: data.limit,
        model_name: data.modelName,
        prompt_version: data.promptVersion,
        weight_config_hash: data.weightConfigHash,
        include_scene: data.includeScene,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Scene Ranking History
   * Return ranking history for a specific scene.
   * @param data The data for the request.
   * @param data.sceneId
   * @param data.limit
   * @param data.newestFirst
   * @param data.includeScene
   * @returns SceneRankingListResponse Successful Response
   * @throws ApiError
   */
  public static listSceneRankingHistory(
    data: SceneRankingsListSceneRankingHistoryData,
  ): CancelablePromise<SceneRankingsListSceneRankingHistoryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/scene-rankings/scene/{scene_id}",
      path: {
        scene_id: data.sceneId,
      },
      query: {
        limit: data.limit,
        newest_first: data.newestFirst,
        include_scene: data.includeScene,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Scene Ranking
   * Fetch a single scene ranking by identifier.
   * @param data The data for the request.
   * @param data.rankingId
   * @param data.includeScene
   * @returns SceneRankingRead Successful Response
   * @throws ApiError
   */
  public static getSceneRanking(
    data: SceneRankingsGetSceneRankingData,
  ): CancelablePromise<SceneRankingsGetSceneRankingResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/scene-rankings/{ranking_id}",
      path: {
        ranking_id: data.rankingId,
      },
      query: {
        include_scene: data.includeScene,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}
