// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

/**
 * Schema for updating image approval status.
 */
export type GeneratedImageApprovalUpdate = {
  /**
   * Approval status: true (approved), false (rejected), null (clear approval)
   */
  user_approved: boolean | null
}

/**
 * Request schema for triggering image generation.
 */
export type GeneratedImageGenerateRequest = {
  book_slug?: string | null
  chapter_range?: [number, number] | null
  scene_ids?: Array<string> | null
  prompt_ids?: Array<string> | null
  limit?: number | null
  overwrite?: boolean
  quality?: string
  preferred_style?: string | null
  aspect_ratio?: string | null
  provider?: string
  model?: string
  response_format?: string
  concurrency?: number
  dry_run?: boolean
}

/**
 * Response schema for image generation results.
 */
export type GeneratedImageGenerateResponse = {
  generated_image_ids: Array<string>
  count: number
  dry_run: boolean
}

/**
 * Collection response for generated images with optional metadata.
 */
export type GeneratedImageListResponse = {
  data: Array<GeneratedImageRead>
  meta?: {
    [key: string]: unknown
  }
}

/**
 * Detailed representation of a generated image.
 */
export type GeneratedImageRead = {
  scene_extraction_id: string
  image_prompt_id: string
  book_slug: string
  chapter_number: number
  variant_index: number
  provider: string
  model: string
  size: string
  quality: string
  style: string
  aspect_ratio?: string | null
  response_format: string
  storage_path: string
  file_name: string
  width?: number | null
  height?: number | null
  bytes_approx?: number | null
  checksum_sha256?: string | null
  request_id?: string | null
  error?: string | null
  id: string
  created_at: string
  updated_at: string
  user_approved?: boolean | null
  approval_updated_at?: string | null
}

/**
 * Request schema for triggering a remix of an existing image prompt.
 */
export type GeneratedImageRemixRequest = {
  /**
   * Optional override for number of remix prompt variants to create.
   */
  variants_count?: number | null
  /**
   * If true, return previews without persisting new prompts.
   */
  dry_run?: boolean
}

/**
 * Response schema for remix initiation acknowledgment.
 */
export type GeneratedImageRemixResponse = {
  remix_prompt_ids: Array<string>
  /**
   * Represents the remix request status (accepted when background task scheduled).
   */
  status?: string
  /**
   * Rough estimate of how long the remix generation may take.
   */
  estimated_completion_seconds?: number
}

/**
 * Generated image with full prompt and scene context.
 */
export type GeneratedImageWithContext = {
  image: GeneratedImageRead
  prompt?: ImagePromptSummary | null
  scene?: SceneSummary | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

/**
 * Collection response for image prompts with optional metadata.
 */
export type ImagePromptListResponse = {
  data: Array<ImagePromptRead>
  meta?: {
    [key: string]: unknown
  }
}

/**
 * Detailed representation of an image prompt variant.
 */
export type ImagePromptRead = {
  id: string
  scene_extraction_id: string
  model_vendor: string
  model_name: string
  prompt_version: string
  variant_index: number
  title: string | null
  prompt_text: string
  negative_prompt: string | null
  style_tags: Array<string> | null
  attributes: {
    [key: string]: unknown
  }
  notes: string | null
  context_window: {
    [key: string]: unknown
  }
  raw_response: {
    [key: string]: unknown
  }
  temperature: number | null
  max_output_tokens: number | null
  llm_request_id: string | null
  execution_time_ms: number | null
  created_at: string
  updated_at: string
  scene?: ImagePromptSceneSummary | null
}

/**
 * High-level information about a scene for prompt context.
 */
export type ImagePromptSceneSummary = {
  id: string
  book_slug: string
  chapter_number: number
  chapter_title: string
  scene_number: number
  location_marker: string
  refined?: string | null
  raw: string
}

/**
 * Summary of image prompt for context.
 */
export type ImagePromptSummary = {
  id: string
  prompt_text: string
  style_tags?: Array<string> | null
  attributes?: {
    [key: string]: unknown
  }
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * Bounds for extraction timestamps.
 */
export type SceneExtractionDateRange = {
  earliest: string | null
  latest: string | null
}

/**
 * Available filter options for scene extractions.
 */
export type SceneExtractionFilterOptions = {
  books: Array<string>
  chapters_by_book: {
    [key: string]: Array<number>
  }
  refinement_decisions: Array<string>
  has_refined_options: Array<boolean>
  date_range: SceneExtractionDateRange
}

/**
 * Paginated scene extraction response.
 */
export type SceneExtractionListResponse = {
  data: Array<SceneExtractionRead>
  total: number
  page: number
  page_size: number
}

/**
 * Detailed representation of a scene extraction record.
 */
export type SceneExtractionRead = {
  id: string
  book_slug: string
  source_book_path: string
  chapter_number: number
  chapter_title: string
  chapter_source_name: string | null
  scene_number: number
  location_marker: string
  raw: string
  refined: string | null
  refinement_decision: string | null
  refinement_rationale: string | null
  chunk_index: number
  chunk_paragraph_start: number
  chunk_paragraph_end: number
  raw_word_count: number | null
  raw_char_count: number | null
  refined_word_count: number | null
  refined_char_count: number | null
  raw_signature: string | null
  provisional_id: number | null
  location_marker_normalized: string | null
  scene_paragraph_start: number | null
  scene_paragraph_end: number | null
  scene_word_start: number | null
  scene_word_end: number | null
  extraction_model: string | null
  extraction_temperature: number | null
  refinement_model: string | null
  refinement_temperature: number | null
  extracted_at: string
  refined_at: string | null
  refinement_has_refined_excerpt: boolean | null
  props?: {
    [key: string]: unknown
  }
}

/**
 * Collection response for scene rankings with optional metadata.
 */
export type SceneRankingListResponse = {
  data: Array<SceneRankingRead>
  meta?: {
    [key: string]: unknown
  }
}

/**
 * Detailed representation of a scene ranking record.
 */
export type SceneRankingRead = {
  id: string
  scene_extraction_id: string
  model_vendor: string
  model_name: string
  prompt_version: string
  justification: string | null
  scores: {
    [key: string]: number
  }
  overall_priority: number
  weight_config: {
    [key: string]: number
  }
  weight_config_hash: string
  warnings: Array<string> | null
  character_tags: Array<string> | null
  raw_response: {
    [key: string]: unknown
  }
  execution_time_ms: number | null
  temperature: number | null
  llm_request_id: string | null
  created_at: string
  updated_at: string
  scene?: SceneRankingSceneSummary | null
}

/**
 * High-level information about a ranked scene.
 */
export type SceneRankingSceneSummary = {
  id: string
  book_slug: string
  chapter_number: number
  chapter_title: string
  scene_number: number
  location_marker: string
  refined: string | null
  raw: string
  refinement_decision?: string | null
}

/**
 * Summary of scene for context.
 */
export type SceneSummary = {
  id: string
  book_slug: string
  chapter_number: number
  chapter_title: string
  scene_number: number
  location_marker: string
  raw: string
  refined?: string | null
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type GeneratedImagesListGeneratedImagesData = {
  approval?: boolean | null
  book?: string | null
  chapter?: number | null
  limit?: number
  model?: string | null
  newestFirst?: boolean
  offset?: number | null
  promptId?: string | null
  provider?: string | null
  sceneId?: string | null
}

export type GeneratedImagesListGeneratedImagesResponse =
  GeneratedImageListResponse

export type GeneratedImagesGetGeneratedImageData = {
  imageId: string
  includePrompt?: boolean
  includeScene?: boolean
}

export type GeneratedImagesGetGeneratedImageResponse = GeneratedImageWithContext

export type GeneratedImagesUpdateImageApprovalData = {
  imageId: string
  requestBody: GeneratedImageApprovalUpdate
}

export type GeneratedImagesUpdateImageApprovalResponse = GeneratedImageRead

export type GeneratedImagesStreamGeneratedImageFileData = {
  imageId: string
}

export type GeneratedImagesStreamGeneratedImageFileResponse = unknown

export type GeneratedImagesListGeneratedImagesForSceneData = {
  includePrompt?: boolean
  includeScene?: boolean
  limit?: number
  model?: string | null
  newestFirst?: boolean
  offset?: number | null
  provider?: string | null
  sceneId: string
}

export type GeneratedImagesListGeneratedImagesForSceneResponse =
  GeneratedImageListResponse

export type GeneratedImagesListGeneratedImagesForPromptData = {
  limit?: number
  model?: string | null
  newestFirst?: boolean
  offset?: number | null
  promptId: string
  provider?: string | null
}

export type GeneratedImagesListGeneratedImagesForPromptResponse =
  GeneratedImageListResponse

export type GeneratedImagesRemixGeneratedImageData = {
  imageId: string
  requestBody?: GeneratedImageRemixRequest | null
}

export type GeneratedImagesRemixGeneratedImageResponse =
  GeneratedImageRemixResponse

export type GeneratedImagesTriggerImageGenerationData = {
  requestBody: GeneratedImageGenerateRequest
}

export type GeneratedImagesTriggerImageGenerationResponse =
  GeneratedImageGenerateResponse

export type ImagePromptsListPromptsForSceneData = {
  includeScene?: boolean
  limit?: number
  modelName?: string | null
  newestFirst?: boolean
  promptVersion?: string | null
  sceneId: string
}

export type ImagePromptsListPromptsForSceneResponse = ImagePromptListResponse

export type ImagePromptsListPromptsForBookData = {
  bookSlug: string
  chapterNumber?: number | null
  includeScene?: boolean
  limit?: number
  modelName?: string | null
  newestFirst?: boolean
  offset?: number | null
  promptVersion?: string | null
  styleTag?: string | null
}

export type ImagePromptsListPromptsForBookResponse = ImagePromptListResponse

export type ImagePromptsGetImagePromptData = {
  includeScene?: boolean
  promptId: string
}

export type ImagePromptsGetImagePromptResponse = ImagePromptRead

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type SceneExtractionsListSceneExtractionsData = {
  bookSlug?: string | null
  chapterNumber?: number | null
  decision?: string | null
  endDate?: string | null
  hasRefined?: boolean | null
  order?: "asc" | "desc"
  page?: number
  pageSize?: number
  search?: string | null
  startDate?: string | null
}

export type SceneExtractionsListSceneExtractionsResponse =
  SceneExtractionListResponse

export type SceneExtractionsGetFilterOptionsResponse =
  SceneExtractionFilterOptions

export type SceneExtractionsGetSceneExtractionData = {
  sceneId: string
}

export type SceneExtractionsGetSceneExtractionResponse = SceneExtractionRead

export type SceneRankingsListTopSceneRankingsData = {
  bookSlug: string
  includeScene?: boolean
  limit?: number
  modelName?: string | null
  promptVersion?: string | null
  weightConfigHash?: string | null
}

export type SceneRankingsListTopSceneRankingsResponse = SceneRankingListResponse

export type SceneRankingsListSceneRankingHistoryData = {
  includeScene?: boolean
  limit?: number
  newestFirst?: boolean
  sceneId: string
}

export type SceneRankingsListSceneRankingHistoryResponse =
  SceneRankingListResponse

export type SceneRankingsGetSceneRankingData = {
  includeScene?: boolean
  rankingId: string
}

export type SceneRankingsGetSceneRankingResponse = SceneRankingRead

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
