// This file is auto-generated by @hey-api/openapi-ts

/**
 * Settings payload bundled with active art styles.
 */
export type AppSettingsBundleResponse = {
    settings: AppSettingsRead;
    art_styles: Array<ArtStyleRead>;
};

/**
 * Detailed representation of current global settings.
 */
export type AppSettingsRead = {
    id: string;
    default_scenes_per_run: number;
    default_art_style_id: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Patch payload for updating global defaults.
 */
export type AppSettingsUpdateRequest = {
    default_scenes_per_run?: (number | null);
    default_art_style_id?: (string | null);
};

/**
 * Collection response for art styles.
 */
export type ArtStyleListResponse = {
    data: Array<ArtStyleRead>;
};

/**
 * Detailed representation of an art style entry.
 */
export type ArtStyleRead = {
    id: string;
    slug: string;
    display_name: string;
    description: (string | null);
    is_recommended: boolean;
    is_active: boolean;
    sort_order: number;
    created_at: string;
    updated_at: string;
};

export type Body_generated_images_crop_image = {
    file: (Blob | File);
};

/**
 * Per-document counts for each pipeline output stage.
 */
export type DocumentDashboardCounts = {
    extracted?: number;
    ranked?: number;
    prompts_generated?: number;
    images_generated?: number;
};

/**
 * Dashboard row for one source document/file.
 */
export type DocumentDashboardEntry = {
    document_id?: (string | null);
    slug: string;
    display_name: string;
    source_path: string;
    source_type: string;
    file_exists: boolean;
    ingestion_state?: (string | null);
    ingestion_error?: (string | null);
    counts?: DocumentDashboardCounts;
    stages?: DocumentDashboardStages;
    last_run?: (DocumentDashboardRunSummary | null);
};

/**
 * Collection response for document dashboard rows.
 */
export type DocumentDashboardResponse = {
    data: Array<DocumentDashboardEntry>;
    total: number;
};

/**
 * Latest pipeline-run summary for a document.
 */
export type DocumentDashboardRunSummary = {
    id: string;
    status: string;
    current_stage: (string | null);
    error_message: (string | null);
    usage_summary?: {
        [key: string]: unknown;
    };
    started_at: (string | null);
    completed_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Boolean completion flags for document pipeline stages.
 */
export type DocumentDashboardStages = {
    extracted?: boolean;
    ranked?: boolean;
    prompts_generated?: boolean;
    images_generated?: boolean;
};

/**
 * Schema for updating image approval status.
 */
export type GeneratedImageApprovalUpdate = {
    /**
     * Approval status: true (approved), false (rejected), null (clear approval)
     */
    user_approved: (boolean | null);
};

/**
 * Request schema for initiating a custom remix with user-edited prompt text.
 */
export type GeneratedImageCustomRemixRequest = {
    /**
     * User-provided prompt text to use for the custom remix variant.
     */
    custom_prompt_text: string;
};

/**
 * Response schema for custom remix initiation acknowledgment.
 */
export type GeneratedImageCustomRemixResponse = {
    custom_prompt_id: string;
    /**
     * Represents the custom remix request status (accepted when background task scheduled).
     */
    status?: string;
    /**
     * Approximate time until the custom remix image is generated.
     */
    estimated_completion_seconds?: number;
};

/**
 * Request schema for triggering image generation.
 */
export type GeneratedImageGenerateRequest = {
    book_slug?: (string | null);
    chapter_range?: ([
    number,
    number
] | null);
    scene_ids?: (Array<(string)> | null);
    prompt_ids?: (Array<(string)> | null);
    limit?: (number | null);
    quality?: string;
    preferred_style?: (string | null);
    aspect_ratio?: (string | null);
    provider?: string;
    model?: string;
    response_format?: string;
    concurrency?: number;
    dry_run?: boolean;
};

/**
 * Response schema for image generation results.
 */
export type GeneratedImageGenerateResponse = {
    generated_image_ids: Array<(string)>;
    count: number;
    dry_run: boolean;
};

/**
 * List item representation of a generated image including prompt metadata.
 */
export type GeneratedImageListItem = {
    scene_extraction_id: string;
    image_prompt_id: string;
    book_slug: string;
    chapter_number: number;
    variant_index: number;
    provider: string;
    model: string;
    size: string;
    quality: string;
    style: string;
    aspect_ratio?: (string | null);
    response_format: string;
    storage_path: string;
    file_name: string;
    width?: (number | null);
    height?: (number | null);
    bytes_approx?: (number | null);
    checksum_sha256?: (string | null);
    request_id?: (string | null);
    error?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
    user_approved?: (boolean | null);
    approval_updated_at?: (string | null);
    file_deleted?: boolean;
    file_deleted_at?: (string | null);
    prompt_title?: (string | null);
    prompt_flavour_text?: (string | null);
    has_been_posted?: boolean;
    is_queued?: boolean;
};

/**
 * Collection response for generated images with optional metadata.
 */
export type GeneratedImageListResponse = {
    data: Array<GeneratedImageListItem>;
    meta?: {
        [key: string]: unknown;
    };
};

/**
 * Detailed representation of a generated image.
 */
export type GeneratedImageRead = {
    scene_extraction_id: string;
    image_prompt_id: string;
    book_slug: string;
    chapter_number: number;
    variant_index: number;
    provider: string;
    model: string;
    size: string;
    quality: string;
    style: string;
    aspect_ratio?: (string | null);
    response_format: string;
    storage_path: string;
    file_name: string;
    width?: (number | null);
    height?: (number | null);
    bytes_approx?: (number | null);
    checksum_sha256?: (string | null);
    request_id?: (string | null);
    error?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
    user_approved?: (boolean | null);
    approval_updated_at?: (string | null);
    file_deleted?: boolean;
    file_deleted_at?: (string | null);
};

/**
 * Request schema for triggering a remix of an existing image prompt.
 */
export type GeneratedImageRemixRequest = {
    /**
     * Optional override for number of remix prompt variants to create.
     */
    variants_count?: (number | null);
    /**
     * If true, return previews without persisting new prompts.
     */
    dry_run?: boolean;
};

/**
 * Response schema for remix initiation acknowledgment.
 */
export type GeneratedImageRemixResponse = {
    remix_prompt_ids: Array<(string)>;
    /**
     * Represents the remix request status (accepted when background task scheduled).
     */
    status?: string;
    /**
     * Rough estimate of how long the remix generation may take.
     */
    estimated_completion_seconds?: number;
};

/**
 * Generated image with full prompt and scene context.
 */
export type GeneratedImageWithContext = {
    image: GeneratedImageRead;
    prompt?: (ImagePromptSummary | null);
    scene?: (SceneSummary | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Collection response for image prompts with optional metadata.
 */
export type ImagePromptListResponse = {
    data: Array<ImagePromptRead>;
    meta?: {
        [key: string]: unknown;
    };
};

/**
 * Detailed representation of an image prompt variant.
 */
export type ImagePromptRead = {
    id: string;
    scene_extraction_id: string;
    model_vendor: string;
    model_name: string;
    prompt_version: string;
    variant_index: number;
    title: (string | null);
    flavour_text: (string | null);
    prompt_text: string;
    negative_prompt: (string | null);
    style_tags: (Array<(string)> | null);
    attributes: {
        [key: string]: unknown;
    };
    notes: (string | null);
    context_window: {
        [key: string]: unknown;
    };
    raw_response: {
        [key: string]: unknown;
    };
    temperature: (number | null);
    max_output_tokens: (number | null);
    llm_request_id: (string | null);
    execution_time_ms: (number | null);
    created_at: string;
    updated_at: string;
    scene?: (ImagePromptSceneSummary | null);
};

/**
 * High-level information about a scene for prompt context.
 */
export type ImagePromptSceneSummary = {
    id: string;
    book_slug: string;
    chapter_number: number;
    chapter_title: string;
    scene_number: number;
    location_marker: string;
    refined?: (string | null);
    raw: string;
};

/**
 * Summary of image prompt for context.
 */
export type ImagePromptSummary = {
    id: string;
    title?: (string | null);
    flavour_text?: (string | null);
    prompt_text: string;
    style_tags?: (Array<(string)> | null);
    attributes?: {
        [key: string]: unknown;
    };
};

/**
 * Request payload for generating multiple metadata variants.
 */
export type MetadataGenerationRequest = {
    variants_count?: number;
    overwrite_existing?: boolean;
};

/**
 * Response payload containing generated metadata variants.
 */
export type MetadataGenerationResponse = {
    prompt_id: string;
    variants: Array<MetadataVariant>;
    count: number;
};

/**
 * Request payload for updating stored metadata.
 */
export type MetadataUpdateRequest = {
    title?: (string | null);
    flavour_text?: (string | null);
};

/**
 * Single metadata variant containing optional title and flavour text.
 */
export type MetadataVariant = {
    title?: (string | null);
    flavour_text?: (string | null);
};

/**
 * Detailed representation of a pipeline run.
 */
export type PipelineRunRead = {
    id: string;
    document_id: (string | null);
    book_slug: (string | null);
    status: string;
    current_stage: (string | null);
    error_message: (string | null);
    config_overrides?: {
        [key: string]: unknown;
    };
    usage_summary?: {
        [key: string]: unknown;
    };
    started_at: (string | null);
    completed_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Request payload for launching a pipeline run.
 */
export type PipelineRunStartRequest = {
    document_id?: (string | null);
    book_slug?: (string | null);
    book_path?: (string | null);
    art_style_id?: (string | null);
    prompts_per_scene?: (number | null);
    ignore_ranking_recommendations?: boolean;
    prompts_for_scenes?: (number | null);
    images_for_scenes?: (number | null);
    skip_extraction?: boolean;
    skip_ranking?: boolean;
    skip_prompts?: boolean;
    quality?: 'standard' | 'hd';
    style?: ('vivid' | 'natural' | null);
    aspect_ratio?: ('1:1' | '9:16' | '16:9' | null);
    mode?: 'batch' | 'sync';
    poll_timeout?: number;
    poll_interval?: number;
    dry_run?: boolean;
};

export type quality = 'standard' | 'hd';

export type mode = 'batch' | 'sync';

/**
 * Response schema for posting status query.
 */
export type PostingStatusResponse = {
    posts: Array<SocialMediaPostRead>;
    has_been_posted: boolean;
    is_queued: boolean;
};

/**
 * Response schema for queue for posting action.
 */
export type QueueForPostingResponse = {
    posts: Array<SocialMediaPostRead>;
    message: string;
};

/**
 * Bounds for extraction timestamps.
 */
export type SceneExtractionDateRange = {
    earliest: (string | null);
    latest: (string | null);
};

/**
 * Available filter options for scene extractions.
 */
export type SceneExtractionFilterOptions = {
    books: Array<(string)>;
    chapters_by_book: {
        [key: string]: Array<(number)>;
    };
    refinement_decisions: Array<(string)>;
    has_refined_options: Array<(boolean)>;
    date_range: SceneExtractionDateRange;
};

/**
 * Paginated scene extraction response.
 */
export type SceneExtractionListResponse = {
    data: Array<SceneExtractionRead>;
    total: number;
    page: number;
    page_size: number;
};

/**
 * Detailed representation of a scene extraction record.
 */
export type SceneExtractionRead = {
    id: string;
    book_slug: string;
    source_book_path: string;
    chapter_number: number;
    chapter_title: string;
    chapter_source_name: (string | null);
    scene_number: number;
    location_marker: string;
    raw: string;
    refined: (string | null);
    refinement_decision: (string | null);
    refinement_rationale: (string | null);
    chunk_index: number;
    chunk_paragraph_start: number;
    chunk_paragraph_end: number;
    raw_word_count: (number | null);
    raw_char_count: (number | null);
    refined_word_count: (number | null);
    refined_char_count: (number | null);
    raw_signature: (string | null);
    provisional_id: (number | null);
    location_marker_normalized: (string | null);
    scene_paragraph_start: (number | null);
    scene_paragraph_end: (number | null);
    scene_word_start: (number | null);
    scene_word_end: (number | null);
    extraction_model: (string | null);
    extraction_temperature: (number | null);
    refinement_model: (string | null);
    refinement_temperature: (number | null);
    extracted_at: string;
    refined_at: (string | null);
    refinement_has_refined_excerpt: (boolean | null);
    props?: {
        [key: string]: unknown;
    };
};

/**
 * Collection response for scene rankings with optional metadata.
 */
export type SceneRankingListResponse = {
    data: Array<SceneRankingRead>;
    meta?: {
        [key: string]: unknown;
    };
};

/**
 * Detailed representation of a scene ranking record.
 */
export type SceneRankingRead = {
    id: string;
    scene_extraction_id: string;
    model_vendor: string;
    model_name: string;
    prompt_version: string;
    justification: (string | null);
    scores: {
        [key: string]: (number);
    };
    overall_priority: number;
    weight_config: {
        [key: string]: (number);
    };
    weight_config_hash: string;
    warnings: (Array<(string)> | null);
    character_tags: (Array<(string)> | null);
    raw_response: {
        [key: string]: unknown;
    };
    execution_time_ms: (number | null);
    temperature: (number | null);
    llm_request_id: (string | null);
    created_at: string;
    updated_at: string;
    scene?: (SceneRankingSceneSummary | null);
};

/**
 * High-level information about a ranked scene.
 */
export type SceneRankingSceneSummary = {
    id: string;
    book_slug: string;
    chapter_number: number;
    chapter_title: string;
    scene_number: number;
    location_marker: string;
    refined: (string | null);
    raw: string;
    refinement_decision?: (string | null);
};

/**
 * Summary of scene for context.
 */
export type SceneSummary = {
    id: string;
    book_slug: string;
    chapter_number: number;
    chapter_title: string;
    scene_number: number;
    location_marker: string;
    raw: string;
    refined?: (string | null);
};

/**
 * Detailed representation of a social media post record.
 */
export type SocialMediaPostRead = {
    id: string;
    generated_image_id: string;
    service_name: string;
    status: string;
    external_id?: (string | null);
    external_url?: (string | null);
    queued_at: string;
    posted_at?: (string | null);
    last_attempt_at?: (string | null);
    attempt_count: number;
    error_message?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DocumentsGetDocumentsDashboardResponse = (DocumentDashboardResponse);

export type GeneratedImagesListProvidersResponse = (Array<(string)>);

export type GeneratedImagesListGeneratedImagesData = {
    approval?: (boolean | null);
    book?: (string | null);
    chapter?: (number | null);
    limit?: number;
    model?: (string | null);
    newestFirst?: boolean;
    offset?: (number | null);
    posted?: (boolean | null);
    promptId?: (string | null);
    provider?: (string | null);
    sceneId?: (string | null);
};

export type GeneratedImagesListGeneratedImagesResponse = (GeneratedImageListResponse);

export type GeneratedImagesGetGeneratedImageData = {
    imageId: string;
    includePrompt?: boolean;
    includeScene?: boolean;
};

export type GeneratedImagesGetGeneratedImageResponse = (GeneratedImageWithContext);

export type GeneratedImagesUpdateImageApprovalData = {
    imageId: string;
    requestBody: GeneratedImageApprovalUpdate;
};

export type GeneratedImagesUpdateImageApprovalResponse = (GeneratedImageRead);

export type GeneratedImagesStreamGeneratedImageFileData = {
    imageId: string;
};

export type GeneratedImagesStreamGeneratedImageFileResponse = (unknown);

export type GeneratedImagesListGeneratedImagesForSceneData = {
    includePrompt?: boolean;
    includeScene?: boolean;
    limit?: number;
    model?: (string | null);
    newestFirst?: boolean;
    offset?: (number | null);
    provider?: (string | null);
    sceneId: string;
};

export type GeneratedImagesListGeneratedImagesForSceneResponse = (GeneratedImageListResponse);

export type GeneratedImagesListGeneratedImagesForPromptData = {
    limit?: number;
    model?: (string | null);
    newestFirst?: boolean;
    offset?: (number | null);
    promptId: string;
    provider?: (string | null);
};

export type GeneratedImagesListGeneratedImagesForPromptResponse = (GeneratedImageListResponse);

export type GeneratedImagesRemixGeneratedImageData = {
    imageId: string;
    requestBody?: (GeneratedImageRemixRequest | null);
};

export type GeneratedImagesRemixGeneratedImageResponse = (GeneratedImageRemixResponse);

export type GeneratedImagesCustomRemixGeneratedImageData = {
    imageId: string;
    requestBody: GeneratedImageCustomRemixRequest;
};

export type GeneratedImagesCustomRemixGeneratedImageResponse = (GeneratedImageCustomRemixResponse);

export type GeneratedImagesTriggerImageGenerationData = {
    requestBody: GeneratedImageGenerateRequest;
};

export type GeneratedImagesTriggerImageGenerationResponse = (GeneratedImageGenerateResponse);

export type GeneratedImagesQueueImageForPostingData = {
    imageId: string;
};

export type GeneratedImagesQueueImageForPostingResponse = (QueueForPostingResponse);

export type GeneratedImagesGetImagePostingStatusData = {
    imageId: string;
};

export type GeneratedImagesGetImagePostingStatusResponse = (PostingStatusResponse);

export type GeneratedImagesRetryFailedPostsData = {
    /**
     * Filter by service (e.g. 'flickr')
     */
    serviceName?: (string | null);
};

export type GeneratedImagesRetryFailedPostsResponse = (QueueForPostingResponse);

export type GeneratedImagesCropImageData = {
    formData: Body_generated_images_crop_image;
    imageId: string;
};

export type GeneratedImagesCropImageResponse = ({
    [key: string]: (string);
});

export type ImagePromptsListPromptsForSceneData = {
    includeScene?: boolean;
    limit?: number;
    modelName?: (string | null);
    newestFirst?: boolean;
    promptVersion?: (string | null);
    sceneId: string;
};

export type ImagePromptsListPromptsForSceneResponse = (ImagePromptListResponse);

export type ImagePromptsListPromptsData = {
    bookSlug?: (string | null);
    chapterNumber?: (number | null);
    includeScene?: boolean;
    limit?: number;
    modelName?: (string | null);
    newestFirst?: boolean;
    offset?: (number | null);
    promptVersion?: (string | null);
    styleTag?: (string | null);
};

export type ImagePromptsListPromptsResponse = (ImagePromptListResponse);

export type ImagePromptsListPromptsForBookData = {
    bookSlug: string;
    chapterNumber?: (number | null);
    includeScene?: boolean;
    limit?: number;
    modelName?: (string | null);
    newestFirst?: boolean;
    offset?: (number | null);
    promptVersion?: (string | null);
    styleTag?: (string | null);
};

export type ImagePromptsListPromptsForBookResponse = (ImagePromptListResponse);

export type ImagePromptsGetImagePromptData = {
    includeScene?: boolean;
    promptId: string;
};

export type ImagePromptsGetImagePromptResponse = (ImagePromptRead);

export type ImagePromptsGenerateMetadataVariantsData = {
    promptId: string;
    requestBody?: (MetadataGenerationRequest | null);
};

export type ImagePromptsGenerateMetadataVariantsResponse = (MetadataGenerationResponse);

export type ImagePromptsUpdatePromptMetadataData = {
    promptId: string;
    requestBody: MetadataUpdateRequest;
};

export type ImagePromptsUpdatePromptMetadataResponse = (ImagePromptRead);

export type PipelineRunsStartPipelineRunData = {
    requestBody: PipelineRunStartRequest;
};

export type PipelineRunsStartPipelineRunResponse = (PipelineRunRead);

export type PipelineRunsGetPipelineRunData = {
    runId: string;
};

export type PipelineRunsGetPipelineRunResponse = (PipelineRunRead);

export type SceneExtractionsListSceneExtractionsData = {
    bookSlug?: (string | null);
    chapterNumber?: (number | null);
    decision?: (string | null);
    endDate?: (string | null);
    hasRefined?: (boolean | null);
    order?: 'asc' | 'desc';
    page?: number;
    pageSize?: number;
    search?: (string | null);
    startDate?: (string | null);
};

export type SceneExtractionsListSceneExtractionsResponse = (SceneExtractionListResponse);

export type SceneExtractionsGetFilterOptionsResponse = (SceneExtractionFilterOptions);

export type SceneExtractionsGetSceneExtractionData = {
    sceneId: string;
};

export type SceneExtractionsGetSceneExtractionResponse = (SceneExtractionRead);

export type SceneRankingsListTopSceneRankingsData = {
    bookSlug?: (string | null);
    includeScene?: boolean;
    limit?: number;
    modelName?: (string | null);
    promptVersion?: (string | null);
    weightConfigHash?: (string | null);
};

export type SceneRankingsListTopSceneRankingsResponse = (SceneRankingListResponse);

export type SceneRankingsListSceneRankingHistoryData = {
    includeScene?: boolean;
    limit?: number;
    newestFirst?: boolean;
    sceneId: string;
};

export type SceneRankingsListSceneRankingHistoryResponse = (SceneRankingListResponse);

export type SceneRankingsGetSceneRankingData = {
    includeScene?: boolean;
    rankingId: string;
};

export type SceneRankingsGetSceneRankingResponse = (SceneRankingRead);

export type SettingsGetSettingsResponse = (AppSettingsBundleResponse);

export type SettingsUpdateSettingsData = {
    requestBody: AppSettingsUpdateRequest;
};

export type SettingsUpdateSettingsResponse = (AppSettingsBundleResponse);

export type SettingsListArtStylesResponse = (ArtStyleListResponse);

export type UtilsHealthCheckResponse = (boolean);