"""Pydantic schemas for API responses."""

from .app_settings import (
    AppSettingsBundleResponse,
    AppSettingsRead,
    AppSettingsUpdateRequest,
    ArtStyleListsRead,
    ArtStyleListsUpdateRequest,
    ConfigurationCheckRead,
    ConfigurationTestResponse,
)
from .art_style import ArtStyleListResponse, ArtStyleRead
from .common import ApiErrorDetail, ApiErrorResponse, Message
from .document import (
    DocumentCreate,
    DocumentDashboardCounts,
    DocumentDashboardEntry,
    DocumentDashboardResponse,
    DocumentDashboardRunSummary,
    DocumentDashboardStages,
    DocumentDashboardStageStatus,
    DocumentListResponse,
    DocumentRead,
    DocumentStageSyncResponse,
)
from .generated_asset import (
    GeneratedAssetCreate,
    GeneratedAssetListResponse,
    GeneratedAssetRead,
)
from .generated_image import (
    GeneratedImageApprovalUpdate,
    GeneratedImageBase,
    GeneratedImageCreate,
    GeneratedImageCustomRemixRequest,
    GeneratedImageCustomRemixResponse,
    GeneratedImageGenerateRequest,
    GeneratedImageGenerateResponse,
    GeneratedImageListItem,
    GeneratedImageListResponse,
    GeneratedImageRead,
    GeneratedImageRemixRequest,
    GeneratedImageRemixResponse,
    GeneratedImageWithContext,
    ImagePromptSummary,
    SceneSummary,
)
from .image_prompt import (
    ImagePromptListResponse,
    ImagePromptRead,
    ImagePromptSceneSummary,
    MetadataGenerationRequest,
    MetadataGenerationResponse,
    MetadataUpdateRequest,
    MetadataVariant,
)
from .pipeline_run import (
    PipelineRunCreate,
    PipelineRunListResponse,
    PipelineRunRead,
    PipelineRunStartRequest,
)
from .scene_extraction import (
    SceneExtractionDateRange,
    SceneExtractionFilterOptions,
    SceneExtractionListResponse,
    SceneExtractionRead,
    SceneGenerateRequest,
    SceneGenerateResponse,
)
from .scene_ranking import (
    SceneRankingListResponse,
    SceneRankingRead,
    SceneRankingSceneSummary,
)
from .social_media_post import (
    PostingStatusResponse,
    QueueForPostingResponse,
    SocialMediaPostRead,
)

__all__ = [
    "AppSettingsBundleResponse",
    "AppSettingsRead",
    "AppSettingsUpdateRequest",
    "ArtStyleListsRead",
    "ArtStyleListsUpdateRequest",
    "ConfigurationCheckRead",
    "ConfigurationTestResponse",
    "ArtStyleListResponse",
    "ArtStyleRead",
    "ApiErrorDetail",
    "ApiErrorResponse",
    "Message",
    "DocumentCreate",
    "DocumentDashboardCounts",
    "DocumentDashboardEntry",
    "DocumentDashboardResponse",
    "DocumentDashboardRunSummary",
    "DocumentDashboardStageStatus",
    "DocumentDashboardStages",
    "DocumentListResponse",
    "DocumentRead",
    "DocumentStageSyncResponse",
    "GeneratedAssetCreate",
    "GeneratedAssetListResponse",
    "GeneratedAssetRead",
    "SceneExtractionDateRange",
    "SceneExtractionFilterOptions",
    "SceneExtractionListResponse",
    "SceneExtractionRead",
    "SceneGenerateRequest",
    "SceneGenerateResponse",
    "SceneRankingListResponse",
    "SceneRankingRead",
    "SceneRankingSceneSummary",
    "ImagePromptListResponse",
    "ImagePromptRead",
    "ImagePromptSceneSummary",
    "MetadataGenerationRequest",
    "MetadataGenerationResponse",
    "MetadataUpdateRequest",
    "MetadataVariant",
    "PipelineRunCreate",
    "PipelineRunListResponse",
    "PipelineRunRead",
    "PipelineRunStartRequest",
    "GeneratedImageBase",
    "GeneratedImageCreate",
    "GeneratedImageApprovalUpdate",
    "GeneratedImageGenerateRequest",
    "GeneratedImageGenerateResponse",
    "GeneratedImageCustomRemixRequest",
    "GeneratedImageCustomRemixResponse",
    "GeneratedImageListResponse",
    "GeneratedImageRead",
    "GeneratedImageListItem",
    "GeneratedImageRemixRequest",
    "GeneratedImageRemixResponse",
    "GeneratedImageWithContext",
    "ImagePromptSummary",
    "SceneSummary",
    "PostingStatusResponse",
    "QueueForPostingResponse",
    "SocialMediaPostRead",
]
