"""add image_generation_batches table

Revision ID: 4df9d25b460c
Revises: 152af98f7667
Create Date: 2026-02-11 10:31:49.228212

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4df9d25b460c'
down_revision = '152af98f7667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generation_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('openai_batch_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('openai_input_file_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('openai_output_file_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('openai_error_file_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('task_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('quality', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('style', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('completed_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('book_slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_generation_batches_book_slug'), 'image_generation_batches', ['book_slug'], unique=False)
    op.create_index(op.f('ix_image_generation_batches_created_at'), 'image_generation_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_image_generation_batches_openai_batch_id'), 'image_generation_batches', ['openai_batch_id'], unique=False)
    op.create_index(op.f('ix_image_generation_batches_status'), 'image_generation_batches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_generation_batches_status'), table_name='image_generation_batches')
    op.drop_index(op.f('ix_image_generation_batches_openai_batch_id'), table_name='image_generation_batches')
    op.drop_index(op.f('ix_image_generation_batches_created_at'), table_name='image_generation_batches')
    op.drop_index(op.f('ix_image_generation_batches_book_slug'), table_name='image_generation_batches')
    op.drop_table('image_generation_batches')
    # ### end Alembic commands ###
