"""Add social_media_posts table

Revision ID: 705b42b7e831
Revises: 5ce7538a9f6b
Create Date: 2026-01-29 10:04:02.009872

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '705b42b7e831'
down_revision = '5ce7538a9f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generated_image_id', sa.Uuid(), nullable=False),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_image_id'], ['generated_images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_image_id', 'service_name', name='uq_social_media_post_image_service')
    )
    op.create_index(op.f('ix_social_media_posts_generated_image_id'), 'social_media_posts', ['generated_image_id'], unique=False)
    op.create_index(op.f('ix_social_media_posts_queued_at'), 'social_media_posts', ['queued_at'], unique=False)
    op.create_index(op.f('ix_social_media_posts_service_name'), 'social_media_posts', ['service_name'], unique=False)
    op.create_index(op.f('ix_social_media_posts_status'), 'social_media_posts', ['status'], unique=False)
    op.drop_constraint('generated_images_scene_extraction_id_fkey', 'generated_images', type_='foreignkey')
    op.drop_constraint('generated_images_image_prompt_id_fkey', 'generated_images', type_='foreignkey')
    op.create_foreign_key(None, 'generated_images', 'image_prompts', ['image_prompt_id'], ['id'])
    op.create_foreign_key(None, 'generated_images', 'scene_extractions', ['scene_extraction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.create_foreign_key('generated_images_image_prompt_id_fkey', 'generated_images', 'image_prompts', ['image_prompt_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('generated_images_scene_extraction_id_fkey', 'generated_images', 'scene_extractions', ['scene_extraction_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_social_media_posts_status'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_service_name'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_queued_at'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_generated_image_id'), table_name='social_media_posts')
    op.drop_table('social_media_posts')
    # ### end Alembic commands ###
