"""Add scene extractions table

Revision ID: 90b99ad3e9cf
Revises: 1a31ce608336
Create Date: 2025-10-05 08:07:04.971759

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90b99ad3e9cf'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_extractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_book_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('chapter_title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('chapter_source_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('location_marker', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('refined', sa.Text(), nullable=True),
    sa.Column('refinement_decision', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('refinement_rationale', sa.Text(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_paragraph_start', sa.Integer(), nullable=False),
    sa.Column('chunk_paragraph_end', sa.Integer(), nullable=False),
    sa.Column('raw_word_count', sa.Integer(), nullable=True),
    sa.Column('raw_char_count', sa.Integer(), nullable=True),
    sa.Column('refined_word_count', sa.Integer(), nullable=True),
    sa.Column('refined_char_count', sa.Integer(), nullable=True),
    sa.Column('raw_signature', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('extraction_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('extraction_temperature', sa.Float(), nullable=True),
    sa.Column('refinement_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('refinement_temperature', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_slug', 'chapter_number', 'scene_number', name='uq_scene_extraction_chapter_scene')
    )
    op.create_index(op.f('ix_scene_extractions_book_slug'), 'scene_extractions', ['book_slug'], unique=False)
    op.create_index(op.f('ix_scene_extractions_chapter_number'), 'scene_extractions', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_scene_extractions_scene_number'), 'scene_extractions', ['scene_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_extractions_scene_number'), table_name='scene_extractions')
    op.drop_index(op.f('ix_scene_extractions_chapter_number'), table_name='scene_extractions')
    op.drop_index(op.f('ix_scene_extractions_book_slug'), table_name='scene_extractions')
    op.drop_table('scene_extractions')
    # ### end Alembic commands ###
