/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSceneRankingsImport } from './routes/_layout/scene-rankings'
import { Route as LayoutPromptGalleryImport } from './routes/_layout/prompt-gallery'
import { Route as LayoutGeneratedImagesImport } from './routes/_layout/generated-images'
import { Route as LayoutExtractedScenesImport } from './routes/_layout/extracted-scenes'
import { Route as LayoutScenePromptsSceneIdImport } from './routes/_layout/scene-prompts.$sceneId'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSceneRankingsRoute = LayoutSceneRankingsImport.update({
  path: '/scene-rankings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPromptGalleryRoute = LayoutPromptGalleryImport.update({
  path: '/prompt-gallery',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGeneratedImagesRoute = LayoutGeneratedImagesImport.update({
  path: '/generated-images',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExtractedScenesRoute = LayoutExtractedScenesImport.update({
  path: '/extracted-scenes',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutScenePromptsSceneIdRoute = LayoutScenePromptsSceneIdImport.update({
  path: '/scene-prompts/$sceneId',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/extracted-scenes': {
      preLoaderRoute: typeof LayoutExtractedScenesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/generated-images': {
      preLoaderRoute: typeof LayoutGeneratedImagesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/prompt-gallery': {
      preLoaderRoute: typeof LayoutPromptGalleryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scene-rankings': {
      preLoaderRoute: typeof LayoutSceneRankingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scene-prompts/$sceneId': {
      preLoaderRoute: typeof LayoutScenePromptsSceneIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutExtractedScenesRoute,
    LayoutGeneratedImagesRoute,
    LayoutPromptGalleryRoute,
    LayoutSceneRankingsRoute,
    LayoutIndexRoute,
    LayoutScenePromptsSceneIdRoute,
  ]),
])

/* prettier-ignore-end */
